CREATE USER sample_user WITH SUPERUSER PASSWORD 'sample_password';
CREATE DATABASE sample ENCODING 'UTF8' LC_COLLATE 'C' TEMPLATE 'template0' OWNER 'sample_user';

CREATE USER other_user WITH SUPERUSER PASSWORD 'other_password';
CREATE DATABASE other ENCODING 'UTF8' LC_COLLATE 'C' TEMPLATE 'template0' OWNER 'other_user';
